version: '3.4'

services:
  dgxplanding:
    image: dgxplanding-prod
    build:
      context: dgxp-landing
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
    restart: always