version: '3.4'

services:
  dgxplanding:
    image: dgxplanding
    build:
      context: dgxp-landing
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
